/**
* Google Members Api
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param reason 
 * @param message 
 * @param locationType 
 * @param domain 
 * @param location 
 */

data class ErrorDetails (
    @Json(name = "reason")
    val reason: kotlin.String,
    @Json(name = "message")
    val message: kotlin.String,
    @Json(name = "locationType")
    val locationType: kotlin.String? = null,
    @Json(name = "domain")
    val domain: kotlin.String? = null,
    @Json(name = "location")
    val location: kotlin.String? = null
)

