/**
* Google Members Api
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.ErrorDetails

import com.squareup.moshi.Json
/**
 * 
 * @param message 
 * @param code 
 * @param errors 
 */

data class Error (
    @Json(name = "message")
    val message: kotlin.String,
    @Json(name = "code")
    val code: kotlin.Int,
    @Json(name = "errors")
    val errors: kotlin.Array<ErrorDetails>? = null
)

