/**
* Google Members Api
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.MembershipLevelSnippetDto

import com.squareup.moshi.Json
/**
 * 
 * @param kind 
 * @param etag 
 * @param id 
 * @param snippet 
 */

data class MembershipLevelDto (
    @Json(name = "kind")
    val kind: kotlin.String,
    @Json(name = "etag")
    val etag: kotlin.String,
    @Json(name = "id")
    val id: kotlin.String,
    @Json(name = "snippet")
    val snippet: MembershipLevelSnippetDto
)

