/**
* Google Members Api
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.MembershipLevelDetailsDto

import com.squareup.moshi.Json
/**
 * 
 * @param creatorChannelId 
 * @param levelDetails 
 */

data class MembershipLevelSnippetDto (
    @Json(name = "creatorChannelId")
    val creatorChannelId: kotlin.String,
    @Json(name = "levelDetails")
    val levelDetails: MembershipLevelDetailsDto
)

