/**
* Google Members Api
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param channelId 
 * @param channelUrl 
 * @param displayName 
 * @param profileImageUrl 
 */

data class MemberDetailsDto (
    @Json(name = "channelId")
    val channelId: kotlin.String,
    @Json(name = "channelUrl")
    val channelUrl: kotlin.String,
    @Json(name = "displayName")
    val displayName: kotlin.String,
    @Json(name = "profileImageUrl")
    val profileImageUrl: kotlin.String
)

