/**
* Google Members Api
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.MembershipsDurationAtLevelDto
import org.openapitools.client.models.MembershipsDurationDto

import com.squareup.moshi.Json
/**
 * 
 * @param highestAccessibleLevel 
 * @param highestAccessibleLevelDisplayName 
 * @param membershipsDuration 
 * @param accessibleLevels 
 * @param membershipsDurationAtLevel 
 */

data class MembershipsDetailsDto (
    @Json(name = "highestAccessibleLevel")
    val highestAccessibleLevel: kotlin.String,
    @Json(name = "highestAccessibleLevelDisplayName")
    val highestAccessibleLevelDisplayName: kotlin.String,
    @Json(name = "membershipsDuration")
    val membershipsDuration: MembershipsDurationDto,
    @Json(name = "accessibleLevels")
    val accessibleLevels: kotlin.Array<kotlin.String>? = null,
    @Json(name = "membershipsDurationAtLevel")
    val membershipsDurationAtLevel: kotlin.Array<MembershipsDurationAtLevelDto>? = null
)

